module.exports = {
  name: 'BJOU-APP',
  baseURL: 'http://192.168.0.203:8082',
  userTag: {
    username: 'username',
    usertoken: 'usertoken',
    userpower: 'userpower',
    userid: 'userid',
    useravatar: 'useravatar',
  },
  api: {
    Login: '/login',
    userLogout: '/logout',
    GetLessonDetails: '/course',
    GetOpeningLessons: '/courselist/open',
    GetClosedLessons: '/courselist/due',
    GetBaseInfo: '/config',
    GetCurrentTask: '/task',
    GetAllTask: '/task/all',
    GetForum: '/forum',
    AddNewForum: '/forum/add',
    GetPage: '/page',
    GetUserInfo: '/personal',
    GetMessageCount: '/msg/counts',
    GetMessage: '/msg/notices',
    GetTalkMessage: '/msg/messageList',
    GetConversation: '/msg/messages',
    GetQuiz: '/quiz',
    GetExamination: '/quiz/start',
    GetQuizReview: '/quiz/review',
    GetLastTimeExamination: '/quiz/page',
    GetHomeworkInfo: '/assignment/getInformation',
    GetHomeWorkComments: '/assignment/getComments',
    GetMedalList: '/badge/user',
    GetGroupList: '/assignment/getTeamMembers',
    GetGradeList: '/grade',
    getTeachersList: '/mentors',
    GetMember: '/group/users',

  },
};
