module.exports = {
  name: 'BJOU-APP',
  baseURL: `${cnApiServiceUrl}`,
  userTag: {
    username: 'username',
    usertoken: 'usertoken',
    userpower: 'userpower',
    userid: 'userid',
    useravatar: 'useravatar',
    userloginname: 'userloginname'
  },
  api: {
    Login: '/login',
    userLogout: '/logout',
    GetLessonDetails: '/course',
    GetOpeningLessons: '/courselist/open',
    GetClosedLessons: '/courselist/due',
    GetBaseInfo: '/config',
    GetCurrentTask: '/task',
    GetAllTask: '/task/all',
    GetForum: '/forum',
    GetForumReply: '/forum/comments',
    AddNewForum: '/forum/add',
    ReplyForum: '/forum/postadd',
    UploadFiles: () => cnGetServiceUrl('moodle', '/webservice/upload.php'),
    GetPage: '/page',
    GetUserInfo: '/personal',
    GetMessageCount: '/msg/counts',
    GetMessage: '/msg/notices',
    GetTalkMessage: '/msg/messageList',
    ReadMessage: '/msg/markallread',
    ReadNotice: '/msg/readNotices',
    GetConversation: '/msg/messages',
    SendConversation: '/msg/sendmessages',
    GetQuiz: '/quiz',
    GetExamination: '/quiz/start',
    GetQuizReview: '/quiz/review',
    GetQuizSummary: '/quiz/summary',
    SendQuiz: '/quiz/process',
    GetLastTimeExamination: '/quiz/page',
    GetHomeworkInfo: '/assignment/getInformation',
    GetHomeWorkComments: '/assignment/getComments',
    GetMedalList: '/badge/user',
    GetGroupList: '/assignment/getTeamMembers',
    GetGradeList: '/grade',
    getTeachersList: '/mentors',
    GetMember: '/group/users',
    GetContacts: '/personal/contacts',
    AddContacts: '/personal/addcontacts',
    DeleteContacts: '/personal/delcontacts',
    ADDHomeWork: '/assignment/add',
    UrlApi: 'url',
    GetFeedBack: '/questionnaire',
    GetFeedBackQuestions: '/questionnaire/getquestion',
    GetSuperClass: '/svp',
    GetResource: '/resource',
    GetFeedBackInfos: '/questionnaire/response',
    SendFeedBack: '/questionnaire/submit',
    CompleteFeedBack: '/questionnaire/unfinished',
    SetAvatar: '/personal/update',
    GetAttendance: '/attendance/course',
    GetAttendanceList: '/attendance/courseList',
    GetGradeCourseList: '/grade/courseList',
    AccessTime: '/log/accesstime',
    Log: '/log',
    UpdateInfo: '/personal/updateInfo',
    SendAssing: '/assignment/commit',
    GetSysNotice: 'notic/list',
    OpinionAdd: 'feedback/add',
    SeedOpinionFiles: () => cnGetServiceUrl('manager', '/file/upload'),
    MyOpinionList: '/feedback',
    ManualCompletion: '/cm/completion',
    GetVersion: '/config/appVersion',
    HelpUrl: () => cnGetServiceUrl('help', '/cnvhelp/index.html'),
    GetChoice: '/vote',
    SendChoice: '/vote/submit'
  },
};
